name: ModernChaplaincy
favicon: null
layout_spectrum: 0.90972
typography_spectrum: 0.49874
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d0e4eb'
    - '#8a6b68'
    - '#4b4c60'
    - '#a4a9a5'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
